version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=123
    ports:
      - "1521:1521"
      - "5500:5500"
    networks:
      - todo-app

  todo-app:
    image: todo-app:latest
    container_name: todo-app
    ports:
      - 8080:8080
    depends_on:
      - oracle-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - todo-app

networks:
  todo-app:
    driver: bridge
